# Executable names:
EXE = tsvcsv
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = main.o tsvcsv.o

# Use the cs225 makefile template:
# include ../cs225/make/cs225.mk

main.o: main.cpp preprocess.cpp
	clang++ -g -Wall -Wextra -o0 main.cpp -o main